from app.models import Listing
from app.services.filtering import filter_listings
from app.sources.base import SourceSearchParams


TEST_LISTINGS: tuple[Listing, ...] = (
    Listing(
        source="test",
        external_id="test-001",
        url="https://example.test/listings/test-001",
        title="Студия у метро Трубная",
        property_type="studio",
        rent_price=45000,
        area_sqm=15,
        metro_station="Трубная",
        metro_minutes=7,
        address="Москва, Цветной бульвар, 16",
        latitude=55.7702,
        longitude=37.6206,
        location_verified=True,
    ),
    Listing(
        source="test",
        external_id="test-002",
        url="https://example.test/listings/test-002",
        title="Студия на Чистых прудах",
        property_type="studio",
        rent_price=52000,
        area_sqm=22,
        metro_station="Чистые пруды",
        metro_minutes=9,
        address="Москва, Покровский бульвар, 8",
        latitude=55.7586,
        longitude=37.6441,
        location_verified=True,
    ),
    Listing(
        source="test",
        external_id="test-003",
        url="https://example.test/listings/test-003",
        title="Однокомнатная квартира у Китай-города",
        property_type="one_room",
        rent_price=68000,
        area_sqm=31,
        metro_station="Китай-город",
        metro_minutes=6,
        address="Москва, Солянка, 1/2",
        latitude=55.7518,
        longitude=37.6388,
        location_verified=True,
    ),
    Listing(
        source="test",
        external_id="test-004",
        url="https://example.test/listings/test-004",
        title="Однокомнатная квартира на Арбате",
        property_type="one_room",
        rent_price=85000,
        area_sqm=42,
        metro_station="Смоленская",
        metro_minutes=8,
        address="Москва, Новый Арбат, 22",
        latitude=55.7529,
        longitude=37.5857,
        location_verified=True,
    ),
    Listing(
        source="test",
        external_id="test-005",
        url="https://example.test/listings/test-005",
        title="Студия у Красных Ворот",
        property_type="studio",
        rent_price=95000,
        area_sqm=28,
        metro_station="Красные Ворота",
        metro_minutes=4,
        address="Москва, Садовая-Черногрязская, 13/3",
        latitude=55.7692,
        longitude=37.6497,
        location_verified=True,
    ),
    Listing(
        source="test",
        external_id="test-006",
        url="https://example.test/listings/test-006",
        title="Просторная однокомнатная у Таганской",
        property_type="one_room",
        rent_price=110000,
        area_sqm=55,
        metro_station="Таганская",
        metro_minutes=10,
        address="Москва, Гончарная улица, 26",
        latitude=55.7410,
        longitude=37.6519,
        location_verified=True,
    ),
    Listing(
        source="test",
        external_id="test-007",
        url="https://example.test/listings/test-007",
        title="Студия у МЦК",
        property_type="studio",
        rent_price=62000,
        area_sqm=26,
        metro_station="Шелепиха",
        metro_minutes=12,
        address="Москва, Шелепихинская набережная, 34",
        latitude=55.7572,
        longitude=37.5201,
        location_verified=True,
    ),
    Listing(
        source="test",
        external_id="test-008",
        url="https://example.test/listings/test-008",
        title="Однокомнатная квартира без геометки",
        property_type="one_room",
        rent_price=79000,
        area_sqm=38,
        metro_station="Аэропорт",
        metro_minutes=11,
        address="Москва, улица Усиевича, 18",
        location_verified=False,
    ),
    Listing(
        source="test",
        external_id="test-009",
        url="https://example.test/listings/test-009",
        title="Небольшая студия без геометки",
        property_type="studio",
        rent_price=49000,
        area_sqm=20,
        metro_station="Савёловская",
        metro_minutes=14,
        address="Москва, Новослободская улица, 62",
        location_verified=False,
    ),
    Listing(
        source="test",
        external_id="test-010",
        url="https://example.test/listings/test-010",
        title="Однокомнатная у Речного вокзала",
        property_type="one_room",
        rent_price=88000,
        area_sqm=50,
        metro_station="Речной вокзал",
        metro_minutes=13,
        address="Москва, Фестивальная улица, 22",
        latitude=55.8599,
        longitude=37.4761,
        location_verified=True,
    ),
)


def search_test_listings(params: SourceSearchParams) -> list[Listing]:
    return filter_listings(TEST_LISTINGS, params)
